### ISSUE TITLE
Large delay while uploading files

### ISSUE THREAD

**Issue by pierotofy** [DroneDB/Registry#102]
During a ddb share (with S3 wasabi setup), I noticed that the upload sometimes stalls for several minutes.

The upload of a file arrives at 100% and then stalls. The next file gets processed after more than a few minutes. This happens several times during an upload.

Each file is a simple image, so the stalling is not due to the hash computation and something else is causing it.

```
DJI_0154.JPG [###########################] 100.00% 118.23s
DJI_0164.JPG [###########################] 100.00% 281.79s
...

DJI_0175.JPG [###########################] 100.00% 410.09s
DJI_0188.JPG [###########################] 100.00% 602.00s

```

**Comment by HeDo88TH** [comment]
I tried the exact thing with a large dataset. It's because we perform the upload to S3 after the upload completed on Registry. This causes stalls and delays in the upload process. What we should do is to decouple the two processes using a queue and a background worker. I'm pretty sure that It's not possible to cross-stream the data between HTTP and S3 acting like a proxy, due to protocol limitations. Consider that the upload speeds could be vastly different and some edge cases could happen if we link the two. I will draft a PR with a fix this week

**Comment by HeDo88TH** [comment]
BTW currently we don't have a way to know if a dataset is being uploaded by share when browsing in the web gui. We just see the new images pop up when doing refresh but no indication that there are running upload sessions. Should we mark the dataset as being worked on somehow?

**Comment by pierotofy** [comment]
> Should we mark the dataset as being worked on somehow?

I'd say no.

The queue / background process is a solution. But I think we need to think this more deeply. We often need FAST access to frequently accessed data. It needs to be cached somehow. I don't think we'll get away with a pure S3 file system implementation.

Have you looked into https://docs.min.io/docs/minio-gateway-for-s3.html and https://docs.min.io/docs/minio-disk-cache-guide.html yet?

**Comment by HeDo88TH** [comment]
I think this is the path to go. We can abstract away the FS implementation details but local and S3 are fundamentally different in terms of latency. The production environment should then have minio backed up by remote S3 (wasabi). I'll work on this after closing the current issues.

**Comment by pierotofy** [comment]
- [ ] Setup a minio gateway setup (a new hub) and test with gatling to evaluate performance.
