### ISSUE TITLE
Large delay while downloading files

### ISSUE THREAD

**Issue by pierotofy** [DroneDB/Registry#103]
While downloading files from registry (with wasabi S3) it takes a significant amount of time to begin the download. 

https://testhub.dronedb.app/r/pierotofy/57esmwmhjc3wwxlc

(Try downloading the entire dataset).

This happens also if you download it a second time.

It should be possible to start streaming files as soon as the first file is downloaded from S3 instead of waiting for all of them?

(Same dataset on MiniReg: https://testhub1.dronedb.app/r/pierotofy/bde139e793c24562854a4bcc4a5e623b)

**Comment by HeDo88TH** [comment]
It is not possible to stream a zip file when it is not completed, It would corrupt itself. We can use a GZipped stream instead but I don't know if it fits our use case. The archiving process does download all the files sequentially and zips them. We can make it multi threaded in order to leverage the entire server bandwidth and speed up the process.

**Comment by pierotofy** [comment]
>  We can make it multi threaded in order to leverage the entire server bandwidth and speed up the process.

You'll have issues of 503 slow down.

> It is not possible to stream a zip file when it is not completed,

I do this with https://github.com/DroneDB/MiniReg/blob/master/libs/dataset.js#L58
