### ISSUE TITLE
Add support for Accept-Ranges while downloading files

### ISSUE THREAD

**Issue by pierotofy** [DroneDB/Registry#165]
Download accelerators require accept-ranges requests which currently are not available while downloading files.

It's also handy for making partial requests with COG files (Cloud Optimized GeoTIFFs) so that the entire file does not have to be downloaded.

**Comment by HeDo88TH** [comment]
It has to be implemented separately because we are streaming the file content while compressing / downloading it. So it is basically a stream of data as fast as our storage (local or s3) can provide.
In order to make this work we should add support for range requests at storage abstraction level. It will be impossible in zip files but a single file download can support ranges

**Comment by pierotofy** [comment]
Yeah there should be no support for .zip files. But it should be available for downloads and access to build files. See for an implementation in the S3 bridge. https://github.com/DroneDB/Registry/pull/199/commits/d3f64a09bc0f7d5aa4ead1a63d93ad02d0777e32
