### ISSUE TITLE
Inconsistent unauthorized responses

### ISSUE THREAD

**Issue by pierotofy** [DroneDB/Registry#43]
`POST /users/authenticate` returns 401 unauthorized with JSON:

```
{
    "error": "Unauthorized"
}
```

On unsuccessful login.

`POST /ddb/share/init` (and others) returns 401 unauthorized without anything.

I had already fixed this. Not sure why this was removed? https://github.com/DroneDB/Registry/commit/16aa43d214a804ddfbd66c50109f085d2b748715

It is useful for a client to know why authorization was denied. Is it a permission issue? Is is invalid credentials? Session timeout? Some other error?

An error field does that.

**Comment by HeDo88TH** [comment]
There are different 401 errors. The first type is that given by the Authentication Provider via the `[Authorize]` attribute on the controller class. The latter is returned by the code when specific conditions are met, like when a user tries to access an organization that does not belong to him.

The first 401 does not provide a body because it is auto-generated. That `AuthenticationMiddleware` adds a body to that response.
In the next future we are going to remove the `[Authorize]` attribute entirely because we will be managing the anonymous users by ourselves.
Therefore there is no need now to fix this issue because it will be solved by itself in the next week.
Plus, adding a new, non necessary middleware to the pipeline slows it down and could lead to more issues.
