### ISSUE TITLE
FileSystem API

### ISSUE THREAD

**Issue by pierotofy** [DroneDB/Registry#96]
This one keeps coming up from user feedback; ability to operate on the dataset files just like a normal file system.

Operations to support at minimum:
 - [ ] Create (upload) new files
 - [ ] Create new folders
 - [ ] Delete existing files / folders
 - [ ] Rename files / folders

**Comment by HeDo88TH** [comment]
Basically everything mentioned is already in Registry. We have `CRUD` on objects (entries) except editing (no `put` endpoint).
I will check if the creation of folders is supported, because Registry expects every file to have a body.
I'm going to update the documentation to expose all the details of this API and I will propose a new `put` endpoint plus adding support for folder creation in `post` endpoint.

The `put` endpoint will also become handy to support exif editing

**Comment by pierotofy** [comment]
Need to test, add a few operations, etc.
